# Generated by Django 4.2.4 on 2023-09-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
