# Generated by Django 4.2.4 on 2023-09-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_note_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='NoteUser',
        ),
    ]
