# Generated by Django 4.2.4 on 2023-09-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_noteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.noteuser'),
        ),
    ]
