# Generated by Django 4.2.4 on 2023-09-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_note_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='userId',
        ),
    ]
