# Generated by Django 4.2.4 on 2023-09-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_note_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.noteuser'),
        ),
    ]
