# Generated by Django 4.2.4 on 2023-09-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_note_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='userId',
            field=models.ForeignKey(db_column='noteuser_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.noteuser'),
        ),
    ]
